
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    env_file:
      - .env

    environment:
      APP_FRONTEND_URL: http://localhost:5173
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "5173:5173"
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
    
      - pgdata:/var/lib/postgresql/data
      
  flyway:
    image: flyway/flyway:latest
    env_file:
      - .env
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./backend/sql:/flyway/sql
    command: migrate
    depends_on:
      - db

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
    - ./ml-service:/app
    - ./ml-service/output:/app/output

volumes:
  pgdata:
