
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    env_file:
      - .env

    environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
    #   SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
    #   SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    #   JWT_SECRET: ${JWT_SECRET}
    #   MAIL_USERNAME: ${MAIL_USERNAME}
    #   MAIL_PASSWORD: ${MAIL_PASSWORD}
    #   MAIL_FROM: ${MAIL_FROM}
      APP_FRONTEND_URL: http://localhost:5173
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "5173:5173"
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  flyway:
    image: flyway/flyway:latest
    env_file:
      - .env
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./backend/sql:/flyway/sql
    command: migrate
    depends_on:
      - db
      

volumes:
  pgdata:
