apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-user/backend:latest
          ports:
            - containerPort: 8080
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: env-secret