apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: your-dockerhub-user/ml-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: env-secret
          volumeMounts:
            - name: ml-app
              mountPath: /app
            - name: ml-output
              mountPath: /app/output
      volumes:
        - name: ml-app
          emptyDir: {}
        - name: ml-output
          emptyDir: {}